name: Test Reports

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - '**.md'
      - '**.rst'
      - '**.ipynb'

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'
          cache-dependency-path: 'requirements*.txt'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov genbadge
          pip install tensorflow
          pip install -r requirements.txt
          pip install -r requirements-extras.txt
          pip install -r requirements-dev.txt
      - name: Run tests
        run: |
          rm -rf test-reports/
          scripts/test-reports.sh
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: ./test-reports/
